# Generated by Django 4.2.4 on 2023-08-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCs',
            fields=[
                ('GC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('GC_Name', models.CharField(max_length=100)),
                ('GC_Type', models.CharField(max_length=10)),
                ('GC_Photo', models.ImageField(upload_to='assets/')),
                ('GC_Desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Score_Board',
            fields=[
                ('GC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Points_Array', models.JSONField()),
            ],
        ),
    ]
