# Generated by Django 4.2.4 on 2023-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_gcs_score_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcs',
            name='GC_Photo',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
    ]
