# Generated by Django 4.2.4 on 2023-08-29 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_gcs_gc_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=25)),
                ('long_name', models.CharField(blank=True, max_length=100)),
                ('Total_Points', models.IntegerField(default=0, max_length=5000)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
